name: taxi_maroc
description: Application Taxi Maroc pour les passagers et les chauffeurs (petits et grands taxis).
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.6.0
  flutter_map: ^8.3.2
  latlong2: ^0.10.1
  share_plus: ^13.3.1
  url_launcher: ^6.3.2
  speech_to_text: ^7.5.0
  flutter_tts: ^4.2.5
  geolocator: ^14.1.1
  qr_flutter: ^4.1.0
  audioplayers: ^6.8.1
  google_maps_flutter: ^2.18.2
  google_maps_flutter_android: ^2.21.0
  google_maps_flutter_platform_interface: ^2.17.0
  flutter_local_notifications: ^22.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/drivers/
    - assets/sounds/
    - assets/map/
