/// Indicatifs téléphoniques internationaux (liste UIT) : code ISO du pays, indicatif, nom en français et en anglais.
/// Maroc (+212) en premier, puis les autres pays par ordre alphabétique (en français).
class DialCode {
  const DialCode(this.iso, this.dial, this.fr, this.en);
  final String iso;
  final String dial;
  final String fr;
  final String en;

  /// Drapeau à partir du code ISO (deux lettres régionales).
  String get flag => String.fromCharCodes(iso.codeUnits.map((c) => 0x1F1E6 + c - 0x41));

  /// « +212 », ou « +1 264 » pour les pays du plan de numérotation nord-américain.
  String get code => dial.length == 4 && dial.startsWith('1') ? '+1 ${dial.substring(1)}' : '+$dial';

  /// Nom en français pour l'application en français, en anglais pour les autres langues.
  String name(String lang) => lang == 'fr' ? fr : en;
}

const dialCodes = [
  DialCode('MA', '212', 'Maroc', 'Morocco'),
  DialCode('AF', '93', 'Afghanistan', 'Afghanistan'),
  DialCode('ZA', '27', 'Afrique du Sud', 'South Africa'),
  DialCode('AX', '358', 'Åland', 'Åland Islands'),
  DialCode('AL', '355', 'Albanie', 'Albania'),
  DialCode('DZ', '213', 'Algérie', 'Algeria'),
  DialCode('DE', '49', 'Allemagne', 'Germany'),
  DialCode('AD', '376', 'Andorre', 'Andorra'),
  DialCode('AO', '244', 'Angola', 'Angola'),
  DialCode('AI', '1264', 'Anguilla', 'Anguilla'),
  DialCode('AG', '1268', 'Antigua-et-Barbuda', 'Antigua and Barbuda'),
  DialCode('SA', '966', 'Arabie saoudite', 'Saudi Arabia'),
  DialCode('AR', '54', 'Argentine', 'Argentina'),
  DialCode('AM', '374', 'Arménie', 'Armenia'),
  DialCode('AW', '297', 'Aruba', 'Aruba'),
  DialCode('AU', '61', 'Australie', 'Australia'),
  DialCode('AT', '43', 'Autriche', 'Austria'),
  DialCode('AZ', '994', 'Azerbaïdjan', 'Azerbaijan'),
  DialCode('BS', '1242', 'Bahamas', 'Bahamas'),
  DialCode('BH', '973', 'Bahreïn', 'Bahrain'),
  DialCode('BD', '880', 'Bangladesh', 'Bangladesh'),
  DialCode('BB', '1246', 'Barbade', 'Barbados'),
  DialCode('BE', '32', 'Belgique', 'Belgium'),
  DialCode('BZ', '501', 'Belize', 'Belize'),
  DialCode('BJ', '229', 'Bénin', 'Benin'),
  DialCode('BM', '1441', 'Bermudes', 'Bermuda'),
  DialCode('BT', '975', 'Bhoutan', 'Bhutan'),
  DialCode('BY', '375', 'Biélorussie', 'Belarus'),
  DialCode('MM', '95', 'Birmanie', 'Myanmar'),
  DialCode('BO', '591', 'Bolivie', 'Bolivia'),
  DialCode('BA', '387', 'Bosnie-Herzégovine', 'Bosnia and Herzegovina'),
  DialCode('BW', '267', 'Botswana', 'Botswana'),
  DialCode('BR', '55', 'Brésil', 'Brazil'),
  DialCode('BN', '673', 'Brunei', 'Brunei'),
  DialCode('BG', '359', 'Bulgarie', 'Bulgaria'),
  DialCode('BF', '226', 'Burkina Faso', 'Burkina Faso'),
  DialCode('BI', '257', 'Burundi', 'Burundi'),
  DialCode('KH', '855', 'Cambodge', 'Cambodia'),
  DialCode('CM', '237', 'Cameroun', 'Cameroon'),
  DialCode('CA', '1', 'Canada', 'Canada'),
  DialCode('CV', '238', 'Cap-Vert', 'Cape Verde'),
  DialCode('CL', '56', 'Chili', 'Chile'),
  DialCode('CN', '86', 'Chine', 'China'),
  DialCode('CY', '357', 'Chypre', 'Cyprus'),
  DialCode('CO', '57', 'Colombie', 'Colombia'),
  DialCode('KM', '269', 'Comores', 'Comoros'),
  DialCode('CG', '242', 'Congo', 'Congo'),
  DialCode('KP', '850', 'Corée du Nord', 'North Korea'),
  DialCode('KR', '82', 'Corée du Sud', 'South Korea'),
  DialCode('CR', '506', 'Costa Rica', 'Costa Rica'),
  DialCode('CI', '225', 'Côte d\'Ivoire', 'Ivory Coast'),
  DialCode('HR', '385', 'Croatie', 'Croatia'),
  DialCode('CU', '53', 'Cuba', 'Cuba'),
  DialCode('CW', '599', 'Curaçao', 'Curaçao'),
  DialCode('DK', '45', 'Danemark', 'Denmark'),
  DialCode('DJ', '253', 'Djibouti', 'Djibouti'),
  DialCode('DM', '1767', 'Dominique', 'Dominica'),
  DialCode('EG', '20', 'Égypte', 'Egypt'),
  DialCode('AE', '971', 'Émirats arabes unis', 'United Arab Emirates'),
  DialCode('EC', '593', 'Équateur', 'Ecuador'),
  DialCode('ER', '291', 'Érythrée', 'Eritrea'),
  DialCode('ES', '34', 'Espagne', 'Spain'),
  DialCode('EE', '372', 'Estonie', 'Estonia'),
  DialCode('SZ', '268', 'Eswatini', 'Eswatini'),
  DialCode('US', '1', 'États-Unis', 'United States'),
  DialCode('ET', '251', 'Éthiopie', 'Ethiopia'),
  DialCode('FJ', '679', 'Fidji', 'Fiji'),
  DialCode('FI', '358', 'Finlande', 'Finland'),
  DialCode('FR', '33', 'France', 'France'),
  DialCode('GA', '241', 'Gabon', 'Gabon'),
  DialCode('GM', '220', 'Gambie', 'Gambia'),
  DialCode('GE', '995', 'Géorgie', 'Georgia'),
  DialCode('GS', '500', 'Géorgie du Sud-et-les îles Sandwich du Sud', 'South Georgia and the South Sandwich Islands'),
  DialCode('GH', '233', 'Ghana', 'Ghana'),
  DialCode('GI', '350', 'Gibraltar', 'Gibraltar'),
  DialCode('GR', '30', 'Grèce', 'Greece'),
  DialCode('GD', '1473', 'Grenade', 'Grenada'),
  DialCode('GL', '299', 'Groenland', 'Greenland'),
  DialCode('GP', '590', 'Guadeloupe', 'Guadeloupe'),
  DialCode('GU', '1671', 'Guam', 'Guam'),
  DialCode('GT', '502', 'Guatemala', 'Guatemala'),
  DialCode('GG', '44', 'Guernesey', 'Guernsey'),
  DialCode('GN', '224', 'Guinée', 'Guinea'),
  DialCode('GQ', '240', 'Guinée équatoriale', 'Equatorial Guinea'),
  DialCode('GW', '245', 'Guinée-Bissau', 'Guinea-Bissau'),
  DialCode('GY', '592', 'Guyana', 'Guyana'),
  DialCode('GF', '594', 'Guyane française', 'French Guiana'),
  DialCode('HT', '509', 'Haïti', 'Haiti'),
  DialCode('HN', '504', 'Honduras', 'Honduras'),
  DialCode('HK', '852', 'Hong Kong', 'Hong Kong'),
  DialCode('HU', '36', 'Hongrie', 'Hungary'),
  DialCode('CX', '61', 'Île Christmas', 'Christmas Island'),
  DialCode('IM', '44', 'Île de Man', 'Isle of Man'),
  DialCode('NF', '672', 'Île Norfolk', 'Norfolk Island'),
  DialCode('KY', '1345', 'Îles Caïmans', 'Cayman Islands'),
  DialCode('CC', '61', 'Îles Cocos', 'Cocos (Keeling) Islands'),
  DialCode('CK', '682', 'Îles Cook', 'Cook Islands'),
  DialCode('FO', '298', 'Îles Féroé', 'Faroe Islands'),
  DialCode('FK', '500', 'Îles Malouines', 'Falkland Islands'),
  DialCode('MP', '1670', 'Îles Mariannes du Nord', 'Northern Mariana Islands'),
  DialCode('MH', '692', 'Îles Marshall', 'Marshall Islands'),
  DialCode('PN', '64', 'Îles Pitcairn', 'Pitcairn Islands'),
  DialCode('SB', '677', 'Îles Salomon', 'Solomon Islands'),
  DialCode('TC', '1649', 'Îles Turques-et-Caïques', 'Turks and Caicos Islands'),
  DialCode('VG', '1284', 'Îles Vierges britanniques', 'British Virgin Islands'),
  DialCode('VI', '1340', 'Îles Vierges des États-Unis', 'U.S. Virgin Islands'),
  DialCode('IN', '91', 'Inde', 'India'),
  DialCode('ID', '62', 'Indonésie', 'Indonesia'),
  DialCode('IQ', '964', 'Irak', 'Iraq'),
  DialCode('IR', '98', 'Iran', 'Iran'),
  DialCode('IE', '353', 'Irlande', 'Ireland'),
  DialCode('IS', '354', 'Islande', 'Iceland'),
  DialCode('IL', '972', 'Israël', 'Israel'),
  DialCode('IT', '39', 'Italie', 'Italy'),
  DialCode('JM', '1876', 'Jamaïque', 'Jamaica'),
  DialCode('JP', '81', 'Japon', 'Japan'),
  DialCode('JE', '44', 'Jersey', 'Jersey'),
  DialCode('JO', '962', 'Jordanie', 'Jordan'),
  DialCode('KZ', '7', 'Kazakhstan', 'Kazakhstan'),
  DialCode('KE', '254', 'Kenya', 'Kenya'),
  DialCode('KG', '996', 'Kirghizistan', 'Kyrgyzstan'),
  DialCode('KI', '686', 'Kiribati', 'Kiribati'),
  DialCode('XK', '383', 'Kosovo', 'Kosovo'),
  DialCode('KW', '965', 'Koweït', 'Kuwait'),
  DialCode('RE', '262', 'La Réunion', 'Réunion'),
  DialCode('LA', '856', 'Laos', 'Laos'),
  DialCode('LS', '266', 'Lesotho', 'Lesotho'),
  DialCode('LV', '371', 'Lettonie', 'Latvia'),
  DialCode('LB', '961', 'Liban', 'Lebanon'),
  DialCode('LR', '231', 'Liberia', 'Liberia'),
  DialCode('LY', '218', 'Libye', 'Libya'),
  DialCode('LI', '423', 'Liechtenstein', 'Liechtenstein'),
  DialCode('LT', '370', 'Lituanie', 'Lithuania'),
  DialCode('LU', '352', 'Luxembourg', 'Luxembourg'),
  DialCode('MO', '853', 'Macao', 'Macao'),
  DialCode('MK', '389', 'Macédoine du Nord', 'North Macedonia'),
  DialCode('MG', '261', 'Madagascar', 'Madagascar'),
  DialCode('MY', '60', 'Malaisie', 'Malaysia'),
  DialCode('MW', '265', 'Malawi', 'Malawi'),
  DialCode('MV', '960', 'Maldives', 'Maldives'),
  DialCode('ML', '223', 'Mali', 'Mali'),
  DialCode('MT', '356', 'Malte', 'Malta'),
  DialCode('MQ', '596', 'Martinique', 'Martinique'),
  DialCode('MU', '230', 'Maurice', 'Mauritius'),
  DialCode('MR', '222', 'Mauritanie', 'Mauritania'),
  DialCode('YT', '262', 'Mayotte', 'Mayotte'),
  DialCode('MX', '52', 'Mexique', 'Mexico'),
  DialCode('FM', '691', 'Micronésie', 'Micronesia'),
  DialCode('MD', '373', 'Moldavie', 'Moldova'),
  DialCode('MC', '377', 'Monaco', 'Monaco'),
  DialCode('MN', '976', 'Mongolie', 'Mongolia'),
  DialCode('ME', '382', 'Monténégro', 'Montenegro'),
  DialCode('MS', '1664', 'Montserrat', 'Montserrat'),
  DialCode('MZ', '258', 'Mozambique', 'Mozambique'),
  DialCode('NA', '264', 'Namibie', 'Namibia'),
  DialCode('NR', '674', 'Nauru', 'Nauru'),
  DialCode('NP', '977', 'Népal', 'Nepal'),
  DialCode('NI', '505', 'Nicaragua', 'Nicaragua'),
  DialCode('NE', '227', 'Niger', 'Niger'),
  DialCode('NG', '234', 'Nigeria', 'Nigeria'),
  DialCode('NU', '683', 'Niue', 'Niue'),
  DialCode('NO', '47', 'Norvège', 'Norway'),
  DialCode('NC', '687', 'Nouvelle-Calédonie', 'New Caledonia'),
  DialCode('NZ', '64', 'Nouvelle-Zélande', 'New Zealand'),
  DialCode('OM', '968', 'Oman', 'Oman'),
  DialCode('UG', '256', 'Ouganda', 'Uganda'),
  DialCode('UZ', '998', 'Ouzbékistan', 'Uzbekistan'),
  DialCode('PK', '92', 'Pakistan', 'Pakistan'),
  DialCode('PW', '680', 'Palaos', 'Palau'),
  DialCode('PS', '970', 'Palestine', 'Palestine'),
  DialCode('PA', '507', 'Panama', 'Panama'),
  DialCode('PG', '675', 'Papouasie-Nouvelle-Guinée', 'Papua New Guinea'),
  DialCode('PY', '595', 'Paraguay', 'Paraguay'),
  DialCode('NL', '31', 'Pays-Bas', 'Netherlands'),
  DialCode('BQ', '599', 'Pays-Bas caribéens', 'Caribbean Netherlands'),
  DialCode('PE', '51', 'Pérou', 'Peru'),
  DialCode('PH', '63', 'Philippines', 'Philippines'),
  DialCode('PL', '48', 'Pologne', 'Poland'),
  DialCode('PF', '689', 'Polynésie française', 'French Polynesia'),
  DialCode('PR', '1787', 'Porto Rico', 'Puerto Rico'),
  DialCode('PT', '351', 'Portugal', 'Portugal'),
  DialCode('QA', '974', 'Qatar', 'Qatar'),
  DialCode('CF', '236', 'République centrafricaine', 'Central African Republic'),
  DialCode('CD', '243', 'République démocratique du Congo', 'DR Congo'),
  DialCode('DO', '1809', 'République dominicaine', 'Dominican Republic'),
  DialCode('RO', '40', 'Roumanie', 'Romania'),
  DialCode('GB', '44', 'Royaume-Uni', 'United Kingdom'),
  DialCode('RU', '7', 'Russie', 'Russia'),
  DialCode('RW', '250', 'Rwanda', 'Rwanda'),
  DialCode('EH', '212', 'Sahara occidental', 'Western Sahara'),
  DialCode('BL', '590', 'Saint-Barthélemy', 'Saint Barthélemy'),
  DialCode('KN', '1869', 'Saint-Christophe-et-Niévès', 'Saint Kitts and Nevis'),
  DialCode('SM', '378', 'Saint-Marin', 'San Marino'),
  DialCode('MF', '590', 'Saint-Martin', 'Saint Martin'),
  DialCode('PM', '508', 'Saint-Pierre-et-Miquelon', 'Saint Pierre and Miquelon'),
  DialCode('VC', '1784', 'Saint-Vincent-et-les-Grenadines', 'Saint Vincent and the Grenadines'),
  DialCode('SH', '290', 'Sainte-Hélène', 'Saint Helena'),
  DialCode('LC', '1758', 'Sainte-Lucie', 'Saint Lucia'),
  DialCode('SV', '503', 'Salvador', 'El Salvador'),
  DialCode('WS', '685', 'Samoa', 'Samoa'),
  DialCode('AS', '1684', 'Samoa américaines', 'American Samoa'),
  DialCode('ST', '239', 'Sao Tomé-et-Principe', 'São Tomé and Príncipe'),
  DialCode('SN', '221', 'Sénégal', 'Senegal'),
  DialCode('RS', '381', 'Serbie', 'Serbia'),
  DialCode('SC', '248', 'Seychelles', 'Seychelles'),
  DialCode('SL', '232', 'Sierra Leone', 'Sierra Leone'),
  DialCode('SG', '65', 'Singapour', 'Singapore'),
  DialCode('SX', '1721', 'Sint Maarten', 'Sint Maarten'),
  DialCode('SK', '421', 'Slovaquie', 'Slovakia'),
  DialCode('SI', '386', 'Slovénie', 'Slovenia'),
  DialCode('SO', '252', 'Somalie', 'Somalia'),
  DialCode('SD', '249', 'Soudan', 'Sudan'),
  DialCode('SS', '211', 'Soudan du Sud', 'South Sudan'),
  DialCode('LK', '94', 'Sri Lanka', 'Sri Lanka'),
  DialCode('SE', '46', 'Suède', 'Sweden'),
  DialCode('CH', '41', 'Suisse', 'Switzerland'),
  DialCode('SR', '597', 'Suriname', 'Suriname'),
  DialCode('SJ', '47', 'Svalbard et Jan Mayen', 'Svalbard and Jan Mayen'),
  DialCode('SY', '963', 'Syrie', 'Syria'),
  DialCode('TJ', '992', 'Tadjikistan', 'Tajikistan'),
  DialCode('TW', '886', 'Taïwan', 'Taiwan'),
  DialCode('TZ', '255', 'Tanzanie', 'Tanzania'),
  DialCode('TD', '235', 'Tchad', 'Chad'),
  DialCode('CZ', '420', 'Tchéquie', 'Czechia'),
  DialCode('IO', '246', 'Territoire britannique de l\'océan Indien', 'British Indian Ocean Territory'),
  DialCode('TH', '66', 'Thaïlande', 'Thailand'),
  DialCode('TL', '670', 'Timor oriental', 'Timor-Leste'),
  DialCode('TG', '228', 'Togo', 'Togo'),
  DialCode('TK', '690', 'Tokelau', 'Tokelau'),
  DialCode('TO', '676', 'Tonga', 'Tonga'),
  DialCode('TT', '1868', 'Trinité-et-Tobago', 'Trinidad and Tobago'),
  DialCode('TN', '216', 'Tunisie', 'Tunisia'),
  DialCode('TM', '993', 'Turkménistan', 'Turkmenistan'),
  DialCode('TR', '90', 'Turquie', 'Turkey'),
  DialCode('TV', '688', 'Tuvalu', 'Tuvalu'),
  DialCode('UA', '380', 'Ukraine', 'Ukraine'),
  DialCode('UY', '598', 'Uruguay', 'Uruguay'),
  DialCode('VU', '678', 'Vanuatu', 'Vanuatu'),
  DialCode('VA', '39', 'Vatican', 'Vatican City'),
  DialCode('VE', '58', 'Venezuela', 'Venezuela'),
  DialCode('VN', '84', 'Viêt Nam', 'Vietnam'),
  DialCode('WF', '681', 'Wallis-et-Futuna', 'Wallis and Futuna'),
  DialCode('YE', '967', 'Yémen', 'Yemen'),
  DialCode('ZM', '260', 'Zambie', 'Zambia'),
  DialCode('ZW', '263', 'Zimbabwe', 'Zimbabwe'),
];

/// Indicatif d'un pays (par son code ISO), Maroc par défaut.
DialCode dialCodeFor(String? iso) => dialCodes.firstWhere((d) => d.iso == iso, orElse: () => dialCodes.first);

String _norm(String s) => s
    .toLowerCase()
    .replaceAll(RegExp('[éèêë]'), 'e')
    .replaceAll(RegExp('[àâäå]'), 'a')
    .replaceAll(RegExp('[ôö]'), 'o')
    .replaceAll(RegExp('[îï]'), 'i')
    .replaceAll(RegExp('[ûü]'), 'u')
    .replaceAll('ç', 'c');

/// Recherche par nom (français ou anglais, sans accents), code ISO ou indicatif (« 212 », « +33 »).
List<DialCode> searchDialCodes(String query) {
  final q = _norm(query.trim()).replaceFirst('+', '');
  if (q.isEmpty) return dialCodes;
  return dialCodes
      .where(
          (d) => _norm(d.fr).contains(q) || _norm(d.en).contains(q) || d.iso.toLowerCase() == q || d.dial.startsWith(q))
      .toList();
}
